apiVersion: v1
data:
  config.properties: |
    KAFKA=http://KAFKA-SERVICE
    DAO=http://LOGIN-SERVICE-DAO
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-24T16:09:47Z"
  name: loginserviceproperties
  namespace: default
  resourceVersion: "278629"
  uid: 4c764331-497a-42ad-a10f-ceaa77f5aaaa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: loginservice
  name: loginservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loginservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: loginservice
    spec:
      containers:
      - image: vvenega/loginservice:latest
        name: loginservice
        volumeMounts:
        - name: config-volume
          mountPath: /msconf
        resources:
          limits:
            memory: 256Mi
      volumes:
      - name: config-volume
        configMap:
          name: loginserviceproperties
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: loginservice
  name: loginservice
spec:
  ports:
  - name: 8004-8004
    port: 8004
    protocol: TCP
    targetPort: 8004
  selector:
    app: loginservice
  type: ClusterIP
status:
  loadBalancer: {}
