apiVersion: v1
data:
  config.properties: |-
    KAFKA=http://KAFKA-SERVICE
    DAO=http://LISTINGS-SERVICE-DAO
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-30T20:42:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:config.properties: {}
    manager: kubectl-create
    operation: Update
    time: "2021-06-30T20:42:20Z"
  name: listingserviceproperties
  namespace: default
  resourceVersion: "917140"
  uid: 8f73e732-f67b-407f-a563-296cdb94bc24
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: listingservice
  name: listingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listingservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: listingservice
    spec:
      containers:
      - image: vvenega/listingservice:latest
        name: listingservice
        volumeMounts:
        - name: config-volume
          mountPath: /msconf
        resources:
          limits:
            memory: 256Mi
      volumes:
      - name: config-volume
        configMap:
          name: listingserviceproperties
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: listingservice
  name: listingservice
spec:
  ports:
  - name: 8100-8100
    port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: listingservice
  type: ClusterIP
status:
  loadBalancer: {}
