apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cassandra
    spec:
      containers:
      - image: docker.io/cassandra:3.11.10
        name: cassandra
        ports:
        - containerPort: 9042
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cassandra
  name: cassandra
spec:
  ports:
  - name: 9042-9042
    port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    app: cassandra
  type: ClusterIP
status:
  loadBalancer: {}
