apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ecommunities
  name: ecommunities
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommunities
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ecommunities
    spec:
      containers:
      - image: vvenega/ecommunities:latest
        name: ecommunities
        ports:
        - name: containerport
          containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ecommunities
  name: ecommunities
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: containerport
  selector:
    app: ecommunities
  type: ClusterIP
status:
  loadBalancer: {}
