apiVersion: v1
kind: PersistentVolume
metadata:
  name: listingdaocontainer-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/ecommunities/myfiles/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - pool-3blubqcee-8lxi3
