apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: listingdaocontainer-pvclaim-volume
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
