apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: elasticsearch
    spec:
      volumes:
       - name: task-pv-storage
         persistentVolumeClaim:
           claimName: elasticsearch-data
      initContainers:
      - name: take-data-dir-ownership
        image: elasticsearch:6.8.16
        command: ["sh","-c","mkdir -p /usr/share/elasticsearch/data && chown -R 1000:1000 /usr/share/elasticsearch/data"]
        # Give `grafana` user (id 472) permissions a mounted volume
        # https://github.com/grafana/grafana-docker/blob/master/Dockerfile
        #command:
        #- chown
        #- -R
        #- 472:472
        #- /usr/share/elasticsearch/data
        volumeMounts:
        - name: task-pv-storage
          mountPath: /usr/share/elasticsearch/data
      containers:
      - image: elasticsearch:6.8.16
        name: elasticsearch
        ports:
        - containerPort: 9002
        env:
        - name: discovery.type
          value: single-node
        volumeMounts:
          - mountPath: "/usr/share/elasticsearch/data"
            name: task-pv-storage
        resources:
         limits:
           memory: 1536Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  ports:
  - name: 9200-9200
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: elasticsearch
  type: ClusterIP
status:
  loadBalancer: {}
