apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: eurekaserver
  name: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eurekaserver
    spec:
      containers:
      - image: vvenega/eurekaserver:latest
        name: eurekaserver
        ports:
        - containerPort: 8761
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: eurekaserver
  name: eurekaserver
spec:
  ports:
  - name: 8761-8761
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: eurekaserver
  type: ClusterIP
status:
  loadBalancer: {}
